global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'subhasmit.prusty@gmail.com'
  smtp_auth_username: 'subhasmit.prusty@gmail.com'
  smtp_auth_password: 'tvvtsblcuxfarmyk'
  smtp_require_tls: true

route:
  receiver: 'email-alert'

receivers:
  - name: 'email-alert'
    email_configs:
      - to: '2022dc04334@wilp.bits-pilani.ac.in'
